version: 2.1

jobs:
  build:
   docker:
    - image: cimg/base:2021.04
      auth:
         username: $DOCKER_USERNAME
         password: $DOCKER_PASSWORD
   steps:
        - run: echo "First Step"
        - checkout
        - run: 
           name: Second step
           command: |
             ls -al
             echo '^^^The files in your repo^^^'
        - run: 
           name: build
           command: |
             docker build -t jalak777/simpleweb:v4 .
             docker ps -a
             docker push jalak777/simpleweb:v4
