version: 2.1

jobs:
  build:
   docker:
    - image: cimg/base:2021.04
      # auth:
      #    username: $DOCKERHUB_USERNAME
      #    password: $DOCKERHUB_PASSWORD
   steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true
        - run: 
           name: build
           command: |
             docker build -t jalak777/simpleweb:v4 .
             echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
             docker push jalak777/simpleweb:v5
