version: 2.1

jobs:
  build:
   docker:
    - image: cimg/base:2021.04
      auth:
         username: $Docker
         password: $Docker
   steps:
        - run: echo "First Step"
        - checkout
        - run: 
           name: Second step
           command: |
             ls -al
             echo '^^^The files in your repo^^^'