# CircleCI configuration file
version: 2.1

jobs:
  start:
    docker:
     - image: "cimg/base:2022.05"
       auth:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
        - run: echo "Say hello to YAML!"
  
  end:
    docker:
      - image: "cimg/base:2022.05"
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "bye......."

workflows: 
  start_and_end:
    jobs:
      - start
      - end
        